apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backends
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-applications
    server: "https://kubernetes.default.svc"
  source:
    path: cdc-camel-kafka-demo/core/backends
    repoURL: "https://github.com/ignaciolago/workshop-cdc.git"
    targetRevision: main
  project: default