apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo
    server: "https://kubernetes.default.svc"
  source:
    path: cdc-camel-kafka-demo/tenants/mongodb/
    repoURL: "https://github.com/ignaciolago/workshop-cdc.git"
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true