apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  source:
    path: cdc-camel-kafka-demo/core/operators
    repoURL: "https://github.com/ignaciolago/workshop-cdc.git"
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
