apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-registry
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka
    server: "https://kubernetes.default.svc"
  source:
    path: cdc-camel-kafka-demo/tenants/service-registry
    repoURL: "https://github.com/ignaciolago/demo-kafka.git"
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true